### ISSUE TITLE
Plan for the next version

### ISSUE THREAD

**Issue by pradel** [accounts-js/accounts#107]
We accumulate here all work need to do in order to change our current code base into what was created on https://github.com/js-accounts/next

**Tasks:**
### Migrate all repositories to TS
- [x] accounts/server https://github.com/js-accounts/accounts/pull/108
- [x] accounts/client https://github.com/js-accounts/accounts/pull/108
- [x] accounts/common https://github.com/js-accounts/accounts/pull/108
- [x] accounts/mongo https://github.com/js-accounts/mongo/pull/25
- [x] accounts/rest-express https://github.com/js-accounts/rest/pull/26
- [x] accounts/rest-client https://github.com/js-accounts/rest/pull/26
- [x] accounts/graphql-client https://github.com/js-accounts/graphql/pull/14
- [x] accounts/graphql-api https://github.com/js-accounts/graphql/pull/14
- [ ] accounts/meteor-adapter

### Add new libraries
- [x] accounts/oauth - WIP #112 
- [x] accounts/password - WIP #112 

### Refactor existing libraries
- [x] accounts/rest-express
- [x] accounts/common
- [x] accounts/server
- [x] accounts/mongo

### Docs
- [ ] Update the docs

**Comment by pradel** [comment]
@davidyaha @TimMikeladze

**Comment by pradel** [comment]
@davidyaha is meteor working with the latest version?

**Comment by davidyaha** [comment]
Not sure. Will need to check it out
